### ISSUE TITLE
SQL Error when clicking on a member's name on Who's Online

### ISSUE THREAD

**Issue by MrCraigTunstall** [MattRogowski/MyReactions#30] opened 2016-10-28 22:47 UTC
I get the following error. Also to note I use a custom database table names.

MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1146 - Table mybb_myreactions' doesn't exist
Query:
SELECT mybb_myreactions.*, count(post_reaction_id) as count FROM mybb_myreactions JOIN mybb_post_reactions ON post_reaction_rid = reaction_id AND post_reaction_uid = '2' GROUP BY reaction_id ORDER BY count DESC LIMIT 10
Please contact the MyBB Group for technical support.

**Comment by MattRogowski** [comment] 2016-10-29 10:00
What version are you using? This has already been fixed.

**Comment by MrCraigTunstall** [comment] 2016-10-29 17:16
The one from the MyBB Plugin site.

**Comment by MrCraigTunstall** [comment] 2016-10-29 17:20
Fixed using the GitHub version, but now get this. https://gyazo.com/87698002d8f6112188614999f394130d

**Comment by MattRogowski** [comment] 2016-10-29 17:25
Well yeah the one on here isn't a stable release yet, use the one from the mods site not here. Were you on 0.0.3 before?

**Comment by MrCraigTunstall** [comment] 2016-10-29 17:28
Yeah, was using 0.0.3 which had that error from what I first posted. :)

**Comment by MattRogowski** [comment] 2016-10-29 17:28
Tell a lie, I thought I'd released this but haven't yet.

The fix you need is here https://github.com/MattRogowski/MyReactions/commit/20eb2d3782a0ac4a78162d1caa144de3b7b78e64 however if you're already using the GitHub version, you'll need to copy the new CSS from the myreactions.css file and put it into the stylesheet for your theme.

**Comment by Eldenroot** [comment] 2016-10-31 16:14
Yeah, it works fine with GitHub version. :)

@MattRogowski - I dont wanna push you, but is there any way to get v1.0.0 soon? Thank you for your work, amazing plugin!

**Comment by MattRogowski** [comment] 2016-10-31 16:15
I'll hopefully be able to work on it this week, have had the most mental few weeks at work so haven't had much time for anything else. It will come, don't worry :D

**Comment by Eldenroot** [comment] 2016-10-31 16:17
@MattRogowski - yeah, sure. I understand, these months before the end of the year are the worst :(

Btw - is there any css class for hover in/our effect for who rep button? I would like to show it all the time, but minimized

**Comment by Eldenroot** [comment] 2016-12-11 17:38
This can be closed as well

**Comment by MattRogowski** [comment] 2016-12-30 19:56
Duplicate of #1

**Closed as completed by MattRogowski** 2016-12-30 19:56 UTC
